### ISSUE TITLE
Meals unable to be used in caravans

### ISSUE THREAD

**Issue by SneedSeedFeed** [emipa606/BetterSurvivalMeals#3]
As above, survival meals added by this mod do not count as nutrition and will not be eaten in caravans including vehicle caravans from vehicle framework.

I have checked:
- Simple packaged survival meal (working)
- Vegetarian packaged survival meal (all qualities not working)
- Simple carnivore packaged survival meal (not working)

To recreate simply make a caravan and load on the listed not working meals, they will not count as nutrition and they will not be eaten.

**Comment by emipa606** [comment]
Tested this and had no issues. You may have some other conflict. 
I tested both with a spawned in carnivore packaged survival meal as well as a cooked one. 
Both got eaten when the caravan was hungry.
